export const videoData = [
  {
    title: "Sacrifice For Your Dreams - Andrew Tate Motivation Speech",
    author: "RealStoicMind",
    views: "118k views",
    timestamp: " 3 months ago",
    thumbnail: "/thumbnail.png",
    icon: "/icon.jpg",
  },
  {
    title: "Sacrifice For Your Dreams - Andrew Tate Motivation Speech",
    author: "RealStoicMind",
    views: "118k views",
    timestamp: " 3 months ago",
    thumbnail: "/thumbnail.png",
    icon: "/icon.jpg",
  },{
    title: "Sacrifice For Your Dreams - Andrew Tate Motivation Speech",
    author: "RealStoicMind",
    views: "118k views",
    timestamp: " 3 months ago",
    thumbnail: "/thumbnail.png",
    icon: "/icon.jpg",
  },{
    title: "Sacrifice For Your Dreams - Andrew Tate Motivation Speech",
    author: "RealStoicMind",
    views: "118k views",
    timestamp: " 3 months ago",
    thumbnail: "/thumbnail.png",
    icon: "/icon.jpg",
  },{
    title: "Sacrifice For Your Dreams - Andrew Tate Motivation Speech",
    author: "RealStoicMind",
    views: "118k views",
    timestamp: " 3 months ago",
    thumbnail: "/thumbnail.png",
    icon: "/icon.jpg",
  },{
    title: "Sacrifice For Your Dreams - Andrew Tate Motivation Speech",
    author: "RealStoicMind",
    views: "118k views",
    timestamp: " 3 months ago",
    thumbnail: "/thumbnail.png",
    icon: "/icon.jpg",
  },{
    title: "Sacrifice For Your Dreams - Andrew Tate Motivation Speech",
    author: "RealStoicMind",
    views: "118k views",
    timestamp: " 3 months ago",
    thumbnail: "/thumbnail.png",
    icon: "/icon.jpg",
  },{
    title: "Sacrifice For Your Dreams - Andrew Tate Motivation Speech",
    author: "RealStoicMind",
    views: "118k views",
    timestamp: " 3 months ago",
    thumbnail: "/thumbnail.png",
    icon: "/icon.jpg",
  },
];
